default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project_maverick_development

test:
  <<: *default
  database: project_maverick_test

production:
  <<: *default
  database: project_maverick_production
  username: project_maverick
  password: <%= ENV['PROJECT_MAVERICK_DATABASE_PASSWORD'] %>
