default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project_maverick_development

test:
  <<: *default
  database: project_maverick_test

production:
  <<: *default
  database: <%= ENV['GOOSE_SERVER_DATABASE_NAME'] %>
  host: <%= ENV['GOOSE_SERVER_DATABASE_HOST'] %>
  username: <%= ENV['GOOSE_SERVER_DATABASE_USERNAME'] %>
  password: <%= ENV['GOOSE_SERVER_DATABASE_PASSWORD'] %>
